# Project
group=bl4ckscor3.mod.sit
version=1.5.2
minecraft_version=26.1.2
java_version=25

# Common
license=MIT
mod_id=sit
mod_name=Sit
description=Allows you to sit on slabs and stairs.
mod_author=bl4ckscor3
minecraft_version_range=[26,)
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1
mdg_version=2.0.141
fcap_version=26.1.3
run_dir=../runs
mixin_version=0.13.3+mixin.0.8.5
mixinextras_version=0.3.5

# NeoForge
neoforge_version=26.1.2.27-beta
minimum_neoforge_version=26.1.2.21-beta

# Fabric
loom_version=1.15-SNAPSHOT
fabric_version=0.146.1+26.1.2
fabric_loader_version=0.18.6
modmenu_version=18.0.0-alpha.8

# Gradle
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
