modLoader="javafml"
loaderVersion="[41,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/Sit/blob/1.19/LICENSE"

[[mods]]
	modId="sit"
	version="${file.jarVersion}"
	displayName="Sit"
	description='''Allows you to sit on slabs and stairs.'''
	issueTrackerURL="http://github.com/bl4ckscor3/Sit/issues"
	displayURL="https://curseforge.com/minecraft/mc-mods/sit"
	authors="bl4ckscor3"

[[dependencies.sit]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"