modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory
license="GNU GPL v3.0 https://github.com/bl4ckscor3/Sit/blob/1.17/LICENSE"

[[mods]] #mandatory
	modId="sit" #mandatory
	version="${file.jarVersion}" #mandatory
	displayName="Sit" #mandatory
	description='''Allows you to sit on slabs and stairs.''' #mandatory
	issueTrackerURL="http://github.com/bl4ckscor3/Sit/issues"
	displayURL="https://curseforge.com/minecraft/mc-mods/sit"
	authors="bl4ckscor3"

[[dependencies.sit]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.18)"
    ordering="NONE"
    side="BOTH"