modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory

[[mods]] #mandatory
	modId="sit" #mandatory
	version="v1.3" #mandatory
	displayName="Sit" #mandatory
	description='''Allows you to sit on slabs and stairs.''' #mandatory
	issueTrackerURL="http://github.com/bl4ckscor3/Sit/issues"
	displayURL="http://minecraft.curseforge.com/projects/sit"
	authors="bl4ckscor3"

[[dependencies.sit]]
    modId="forge"
    mandatory=true
    versionRange="[28.0.48,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"