modLoader="javafml"
loaderVersion="[46,)"
license="MIT https://github.com/bl4ckscor3/Sit/blob/1.20/LICENSE"

[[mods]]
	modId="sit"
	version="${file.jarVersion}"
	displayName="Sit"
	description='''Allows you to sit on slabs and stairs.'''
	issueTrackerURL="https://github.com/bl4ckscor3/Sit/issues"
	displayURL="https://curseforge.com/minecraft/mc-mods/sit"
	authors="bl4ckscor3"

[[dependencies.sit]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"