package bl4ckscor3.mod.sit;

import java.util.Arrays;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.EntityRegistry;
import net.minecraftforge.common.MinecraftForge;

@Mod(modid=Sit.modid, name=Sit.name, version=Sit.version, acceptedMinecraftVersions="[" + Sit.mcVersion + "]")
public class Sit
{
	public static final String modid = "sit";
	public static final String name = "Sit";
	public static final String version = "v1.1";
	public static final String mcVersion = "1.7.10";
	@Instance(modid)
	public Sit instance;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		ModMetadata meta = event.getModMetadata();

		meta.authorList = Arrays.asList(new String[]{"bl4ckscor3"});
		meta.autogenerated = false;
		meta.description = "Adds the ability to sit on slabs and stairs.";
		meta.modId = modid;
		meta.name = name;
		meta.version = version;
		MinecraftForge.EVENT_BUS.register(new SitHandler());
	}

	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		EntityRegistry.registerModEntity(EntitySit.class, "entity_sit", 0, instance, 256, 20, false);
	}
}
